* scripts/vagalumectl: Check for dbus-send
* debian/control: Add build dependency on libdbus-glib-1-dev and
recommend dbus.

diff --git a/scripts/vagalumectl b/scripts/vagalumectl
--- a/scripts/vagalumectl
+++ b/scripts/vagalumectl
@@ -92,6 +92,11 @@ if [ $# -lt 1 ]; then
     invalid_params;
 fi
 
+if ! which dbus-send > /dev/null 2>&1; then
+    echo "ERROR: dbus-send not found"
+    exit 1
+fi
+
 # Check the command and execute it
 COMMAND=${1}
 if [ $# -eq 1 ]; then
